FROM node:12
RUN apt update && apt install -y libsecret-1-dev
RUN npm install -g --unsafe-perm @microsoft/rush@5.40.7
COPY ./servers/diplomas/package.json /app/servers/diplomas/package.json
COPY ./apps/holder/package.json /app/apps/holder/package.json
COPY ./apps/issuer/package.json /app/apps/issuer/package.json
COPY ./apps/verifier/package.json /app/apps/verifier/package.json
COPY ./libs/storage/package.json /app/libs/storage/package.json
COPY ./libs/ledger/package.json /app/libs/ledger/package.json
COPY ./libs/crypto/package.json /app/libs/crypto/package.json
COPY ./libs/protocol/package.json /app/libs/protocol/package.json
COPY ./libs/messaging/package.json /app/libs/messaging/package.json
COPY ./libs/design-system/package.json /app/libs/design-system/package.json
COPY rush.json /app/rush.json
WORKDIR /app/
RUN rush update