version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ./mongodb/database:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
  holder:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ediplomas/app:latest
    container_name: holder
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    command: /bin/sh -c 'cd apps/holder && rushx dev'
    depends_on: 
      - server
    links: 
      - server
    environment: 
      SERVERURI: http://server:5000/api/
  issuer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ediplomas/app:latest
    container_name: issuer
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: /bin/sh -c 'cd apps/issuer && rushx dev'
    depends_on: 
      - server
    links: 
      - server
    environment: 
      SERVERURI: http://server:5000/api/
  verifier:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ediplomas/app:latest
    container_name: verifier
    volumes:
      - ./:/app
    ports:
      - 3002:3002
    command: /bin/sh -c 'cd apps/verifier && rushx dev'
    depends_on: 
      - server
    links: 
      - server
    environment: 
      SERVERURI: http://server:5000/api/
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ediplomas/app:latest
    container_name: server
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    command: /bin/sh -c 'cd servers/diplomas && rushx dev'
    depends_on: 
      - mongodb
      - crypto
      - ganache
    links: 
      - mongodb
      - crypto
      - ganache
    environment: 
      MONGOURI: mongodb://mongodb:27017
      ZERORPCURI: tcp://crypto:4242
      GANACHEURI: http://ganache:8545
  ganache:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ediplomas/app:latest
    container_name: ganache
    volumes:
      - ./:/app
    ports:
      - 8545:8545
    command: /bin/sh -c 'cd libs/ledger && rushx ganache'
  crypto:
    build:
      context: ./libs/crypto
      dockerfile: Dockerfile.dev
    image: ediplomas/crypto:latest
    container_name: crypto
    volumes:
      - ./libs/crypto:/app
    ports:
      - 4242:4242

